apiVersion: v1
kind: Pod
metadata:
   name: codeforge-ingress
   labels:
     app: codeforge
spec:
   containers:
   - name: codeforge-ingress
     image: 'YOUR-DOCKER-IMAGE'
 
---

kind: Service
apiVersion: v1
metadata:
  name: codeforge-service
spec:
  selector:
    app: codeforge
  ports:
    - port: 5678
