# apiVersion: v1
# kind: Service
# metadata:
#   name: loki-service
#   labels:
#     app: loki
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 3100
#       targetPort: 3100
#   selector:
#     app: loki
