apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeforge-app
  labels:
    app: codeforge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codeforge-app
  template:
    metadata:
      labels:
        app: codeforge-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: codeforge-app-pod
          image: 604915685483.dkr.ecr.us-east-1.amazonaws.com/codeforge:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
      nodeSelector:
        kubernetes.io/os: linux
