---
apiVersion: v1
kind: Namespace
metadata:
  name: codeforge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: codeforge
  name: deployment-codeforge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: codeforge-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: codeforge-app
    spec:
      containers:
        - name: codeforge-app
          image: moatdev/cf-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  namespace: codeforge
  name: service-codeforge
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: codeforge-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: codeforge
  name: ingress-codeforge
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-codeforge
                port:
                  number: 80
